<?php

namespace Tests\Unit\User;

use App\Models\User;
use App\Repositories\UserRepository;
use Illuminate\Support\Str;
use Tests\TestCase;

class AuthTest extends TestCase
{
   protected $repository;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = new UserRepository(new User);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }

    public function testRegistration(){
         $data = [
             'name'=>'admin',
             'password'=>'123456',
             'email'=>str::randrom(5)."gmail@com",
             'phone' =>(string) rand(1111111111,9999999999)
             ];

         $response = $this->repository->store($data);
         print_r($response);
         $this->assertTrue(true);

    }


    public function testLogin(){
        $data = [
            "phone" => "01521447941",
            "password" =>"123456"
            ];
      $response = $this->repository->generateAuthToken($data);
      print_r($response);

      $this->assertTrue(true);
    }
}
