<?php

namespace Tests\Unit\Excel;



use Tests\TestCase;

class TestFileReadSP extends TestCase
{
   protected $loadFIle ;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testPhpSpreadsheetLoad()
    {

        
        $this->assertTrue(true);
    }
}
